FROM golang:1.21.6-alpine3.18 AS build
WORKDIR /go/src/app
COPY ./src/* .
RUN go mod download
RUN GOOS=linux go build -o /go/bin/app -v .

FROM golang:1.21.6-alpine3.18
COPY --from=build /go/bin/app /go/bin/app
EXPOSE 8080
ENTRYPOINT [ "/go/bin/app" ]