# ============================================
# ÉTAPE 1 : Build (environnement de compilation)
# ============================================
FROM golang:1.24.11-alpine3.21 AS build

# Installer les dépendances de build si nécessaire
RUN apk add --no-cache git

WORKDIR /go/src/app
# COPIE 1 - fichiers de dépendances
COPY src/go.mod src/go.sum ./
RUN go mod download

# COPIE 2 - fichiers sources de l'application
COPY src/* .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/server .

# ============================================
# ÉTAPE 2 : Runtime (environnement d'exécution)
# ============================================
FROM scratch

# Copier uniquement le binaire compilé
COPY --from=build /app/server /server

EXPOSE 8080
ENTRYPOINT ["/server"]